import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';


export default function Home() {
return(
<div>
<Head>
   <title>Aleksandra Miekisiak Portfolio</title>
   <meta name ="description" content="Generated by me"></meta>
   <link rel="icon" href="/favicon.ico"/>
</Head>

<main>
<section className="  bg-slate-800 px-10">
   <nav className="py-10 mb-12 flex justify-between">
<h1 className="text xl">The Dev to die for</h1>
<ul className="flex items-center">
   <li>
      <BsFillMoonStarsFill className="cursor-pointer"></BsFillMoonStarsFill>
   </li>
   <li>
      <a className="bg-cyan-500 bg-gradient-to-tr from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">
      Resume </a>
      </li>
</ul>
</nav>
</section>
</main>
</div>
);
}
